export const HOME_STACK = 'HOME_STACK';
export const TRADE_STACK = 'TRADE_STACK';
export const POOL_STACK = 'POOL_STACK';
export const APP_STACK = 'POOL_STACK';

// COMMON
export const ALERT_SCREEN = 'ALERT_SCREEN';
export const OPTION_SCREEN = 'OPTION_SCREEN';
export const LANGUAGE_SCREEN = 'LANGUAGE_SCREEN';

export const APP_SCREEN = 'APP_SCREEN';
export const SEE_PAIR_SCREEN = 'SEE_PAIR_SCREEN';
export const GOVERNANCE_SCREEN = 'GOVERNANCE_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const SWAP_SCREEN = 'SWAP_SCREEN';
export const SETTING_SWAP_SCREEN = 'SETTING_SWAP_SCREEN';
export const POOL_SCREEN = 'POOL_SCREEN';
export const CREATE_PAIR_SCREEN = 'CREATE_PAIR_SCREEN';
export const ADD_LIQUIDITY_SCREEN = 'ADD_LIQUIDITY_SCREEN';
export const LIST_WALLET_SCREEN = 'LIST_WALLET_SCREEN';
export const SEARCH_COIN_SCREEN = 'SEARCH_COIN_SCREEN';
